files:
  - source: '*'
    ignore:
      - /oc-includes/vendor/*.*
      - /.github
    translation: /oc-content/languages/%locale_with_underscore%/
    translate_content: 0
    translate_attributes: 0
    content_segmentation: 0
